import json
DEVICE = 'cuda:0' # 'cpu'
# DEVICE = 'cpu'
MODEL_PATH = ''
STATE_DQN_PATH = './state_dqn.pth'

with open('cropping.json') as f:
    HP_NUM_COORDS = json.load(f)

'''
*** training parameters
'''
REWARD_IDLE = -0.1
REWARD_DMG_GIVEN = 1
REWARD_DMG_TAKEN = -1
REWARD_KILL_ENEMY = 10000
REWARD_KILL_SELF = -15000

EVALUATION_REWARD_LENGTH = 100
MEMORY_CAPACITY = 100000

TRANSFER_FREQUENCY = 2000
UPDATE_FREQUENCY = 100
# FRAMES_REQUIRED = 10000
FRAMES_REQUIRED = 100
BATCH_SIZE = 1

ACTION_WAIT = 0.25

'''
*** environment parameters
'''
ACTION_SIZE = 26
SCREEN_X = 540
SCREEN_Y = 300
INPUT_X = 540
INPUT_Y = 300
HISTORY_SIZE = 4

'''
*** arduino_driver.py
'''
ON = 0
OFF = 1

LEFT = 0
RIGHT = 1
DOWN = 0
UP = 1

PIN_VMOVE_ENBL = 2
PIN_VMOVE = 3
PIN_HMOVE_ENBL = 4
PIN_HMOVE = 5
PIN_ATTACK = 6
PIN_SPECIAL = 7
PIN_HTILT_ENBL = 8
PIN_HTILT = 9
PIN_VTILT_ENBL = 10
PIN_VTILT = 11
PIN_GRAB = 12
PIN_SHIELD = 13

'''
*** agent.py
'''
EXPLORE_STEP = 100000
EPSILON_START = 1.0
EPSILON_MIN = 0.01
LEARNING_RATE = 0.01
DISCOUNT_FACTOR = 0.99

'''
*** models.py
'''
